allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true
overrides:
  array-includes: npm:@nolyfill/array-includes@latest
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@latest
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@latest
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@latest
  es-iterator-helpers: npm:@nolyfill/es-iterator-helpers@latest
  function-bind: npm:@nolyfill/function-bind@latest
  has: npm:@nolyfill/has@latest
  has-proto: npm:@nolyfill/has-proto@latest
  has-symbols: npm:@nolyfill/has-symbols@latest
  object.assign: npm:@nolyfill/object.assign@latest
  object.entries: npm:@nolyfill/object.entries@latest
  object.fromentries: npm:@nolyfill/object.fromentries@latest
  object.hasown: npm:@nolyfill/object.hasown@latest
  object.values: npm:@nolyfill/object.values@latest
  side-channel: npm:@nolyfill/side-channel@latest
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@latest
